# Allow pods labeled run=backend in namespace default to access cassandra over port 80
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cassandra
  namespace: cassandra
spec:
  podSelector:
    matchLabels:
      run: cassandra
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              ns: default
          podSelector:
            matchLabels:
              run: backend
      ports:
        - protocol: TCP
          port: 80
